name: Secure CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # Default runner (Linux)

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4
      name: Checkout Code

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build
      env:
        NODE_ENV: production

    - name: Security Scan
      run: npm audit --json | tee audit.json | jq '.'
      continue-on-error: true

    - name: Lint Code
      run: npm run lint

    - name: Static Code Analysis
      run: npm run analyze
